### ISSUE TITLE
gob service returns infinite words when limit param not provided

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd-examples#64]

**Comment by esbie** [comment]
huh I thought that was a feature....

**Comment by klingerf** [comment]
From looking at the code, it seems like this is intended. If limit is not specified the gen service will loop indefinitely until the stream is closed.

https://github.com/BuoyantIO/linkerd-examples/blob/master/gob/src/gen/main.go#L59

**Comment by klingerf** [comment]
Oops, talked to @siggy and it sounds like the issue is that the process doesn't respond to interrupts. Reopening.

**Comment by siggy** [comment]
Ok after testing this all works as expected, nevermind.
