### ISSUE TITLE
Error : ip is not found while trying to open linkerd admin dasboard

### ISSUE THREAD

**Issue by andela-ooladayo** [BuoyantIO/linkerd-examples#78]
I got the error below while trying to open admin dashboard according to the instruction on the doc(linkerd-examples/k8s-daemonset)

`error: error executing jsonpath "{.status.loadBalancer.ingress[0].ip}": ip is not found
-bash: open: command not found`

When I check the content of the JSON using:
`kubectl get svc l5d --output=json` 
I discovered that ip has been changed to hostname from kubernetes 1.5.0.

**Comment by wmorgan** [comment]
@andela-ooladayo what version of Kubernetes are you running?

**Comment by andela-ooladayo** [comment]
@wmorgan 1.5.0

**Comment by klingerf** [comment]
Hey @andela-ooladayo, thanks for reporting this. I tried out the k8s configs from this repo on Kubernetes 1.5.2, and the apps loaded successfully for me. Here's what I think is going on:

> `error: error executing jsonpath "{.status.loadBalancer.ingress[0].ip}": ip is not found`

When setting up a Kubernetes service that creates a load balancer, the service is created immediately, but the load balancer is created asynchronously. I've seen it take as long as 5 minutes to acquire an external IP after the service is created. So I think it's possible that the service didn't have an external IP yet when you ran this command, which caused it to fail. We should include a note in the documentation that explains that there might be some delay before the external IP is available.

> `bash: open: command not found`

The `open` command is only available on macOS, and my guess is that you're not running on that OS. We should also update the documentation to make this clearer.

I'll leave this issue open to track updating the documentation. In the meantime, would you mind redeploying to your Kubernetes 1.5 setup, to see if the service picks up an external IP eventually?

**Comment by andela-ooladayo** [comment]
I understand the part where load balancer is not ready,  the error will be different in that case.
Solution:
When I ran kubectl get svc l5d --output=json I got 
```
"status": {
        "loadBalancer": {
            "ingress": [
                {
                    "hostname": "xxxxxxxxxxxxx.us-east-1.elb.amazonaws.com"
                }
            ]
        }
    }
```
Which means the ip have been changed to hostname, so
`open http://$(kubectl get svc l5d -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"):9990` works

**Comment by klingerf** [comment]
@andela-ooladayo Nice find! I was doing my testing on GCE, which sets `ip` but not `hostname`. And it looks like AWS load balancers set `hostname` but not `ip`, based on this documentation:

https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_loadbalanceringress

Good catch. I'll update our docs to reference that when determining the external ip.

**Comment by klingerf** [comment]
For my own reference, it looks like we can update the documentation to:

```
open http://$(kubectl get svc l5d -o jsonpath="{.status.loadBalancer.ingress[0].*}"):9990
```

And I think that should work on both platforms.
